CREATE DATABASE IF NOT EXISTS greglist;
USE greglist;

CREATE TABLE IF NOT EXISTS MEUS_CONTATOS
(
    SOBRENOME VARCHAR(30) NOT NULL DEFAULT 'nobody',
    PRIMEIRO_NOME VARCHAR(20) NOT NULL DEFAULT 'nobody',
    EMAIL VARCHAR(50),
    SEXO CHAR(1),
    ANIVERSARIO DATE,
    PROFISSAO VARCHAR(50),
    ESTADO_CIVIL VARCHAR(20),
    INTERESSES VARCHAR(100),
    PROCURA VARCHAR(100)
);
