USE headfirst_sql;

SELECT STATUS FROM my_contacts GROUP BY STATUS ORDER BY STATUS;

SELECT PROFESSION FROM my_contacts GROUP BY PROFESSION ORDER BY PROFESSION;

SELECT SEEKING FROM my_contacts GROUP BY SEEKING ORDER BY SEEKING;
