USE headfirst_sql;

CREATE TABLE IF NOT EXISTS toys
(
    id_toy INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    toy VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS boys
(
    id_boy INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    boy VARCHAR(20)
);
